[package]

name = "strava"
version = "0.0.1"
authors = ["Joe Wilm <jdwilm@gmail.com>"]

[dependencies.hyper]
git = "https://github.com/hyperium/hyper.git"

[dependencies.rustc-serialize]
version = "0.3"

[dependencies.time]
version = "*"
